# writing buildspec.yml file for pushing image to ECR (docker version: 18, go: 1.19)
# Path: buildspec.yml
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      golang: 1.19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPOSITORY_NAME
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $AWS_ECR_REPOSITORY_NAME .
      - docker tag $AWS_ECR_REPOSITORY_NAME:latest $REPOSITORY_URI:latest
  build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
